
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Jul 02 22:18:29 CST 2014
//----------------------------------------------------

package com.github.gg.compiler.tres;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int BTHAN = 10;
  public static final int MULT = 15;
  public static final int S = 31;
  public static final int COMMENT = 33;
  public static final int KW_CHAR = 26;
  public static final int INT = 3;
  public static final int PRINTLN = 27;
  public static final int H = 30;
  public static final int MINUS = 14;
  public static final int BETHAN = 11;
  public static final int LTHAN = 8;
  public static final int LS = 21;
  public static final int LP = 17;
  public static final int RS = 22;
  public static final int DIV = 16;
  public static final int LL = 24;
  public static final int RP = 18;
  public static final int PLUS = 13;
  public static final int IF = 20;
  public static final int RL = 25;
  public static final int EXP = 36;
  public static final int LETHAN = 9;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int HEAP = 28;
  public static final int EQUAL = 6;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int MOD = 35;
  public static final int STACK = 29;
  public static final int DEQUAL = 7;
  public static final int ERROR = 34;
  public static final int PCOMA = 4;
  public static final int KW_VOID = 38;
  public static final int GOTO = 19;
  public static final int NEQUAL = 12;
  public static final int FLOAT = 37;
  public static final int DPUNTOS = 5;
  public static final int PRINT = 23;
}

