
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 11 13:22:34 CST 2014
//----------------------------------------------------

package com.github.gg.compiler.tres;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int AND = 14;
  public static final int LS = 27;
  public static final int PLUS = 16;
  public static final int RS = 28;
  public static final int OR = 13;
  public static final int INT = 3;
  public static final int THEN = 26;
  public static final int LP = 20;
  public static final int EQUAL = 6;
  public static final int GOTO = 22;
  public static final int RP = 21;
  public static final int LL = 23;
  public static final int NOT = 15;
  public static final int RL = 24;
  public static final int IF = 25;
  public static final int ID = 2;
  public static final int BTHAN = 10;
  public static final int LETHAN = 9;
  public static final int MULT = 18;
  public static final int EOF = 0;
  public static final int NEQUAL = 12;
  public static final int PRINTLN = 30;
  public static final int DIV = 19;
  public static final int MINUS = 17;
  public static final int LTHAN = 8;
  public static final int PRINT = 29;
  public static final int error = 1;
  public static final int BETHAN = 11;
  public static final int DEQUAL = 7;
  public static final int PCOMA = 4;
  public static final int DPUNTOS = 5;
}

