
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Jul 04 20:51:43 CST 2014
//----------------------------------------------------

package com.github.gg.compiler.tres;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int KW_TEXTO = 40;
  public static final int PRINT_BOOLEAN = 47;
  public static final int BTHAN = 10;
  public static final int KW_LINEA = 39;
  public static final int MULT = 15;
  public static final int KW_STRING2INT = 56;
  public static final int COMMENT = 32;
  public static final int KW_INT2BOOLEAN = 51;
  public static final int KW_INT2FLOAT = 49;
  public static final int P = 31;
  public static final int KW_STRING2BOOLEAN = 59;
  public static final int KW_CHAR2STRING = 55;
  public static final int KW_BOOLEAN2STRING = 60;
  public static final int INT = 3;
  public static final int PRINTLN = 27;
  public static final int H = 30;
  public static final int MINUS = 14;
  public static final int BETHAN = 11;
  public static final int LTHAN = 8;
  public static final int KW_LIENZO = 45;
  public static final int LS = 21;
  public static final int KW_STRING2FLOAT = 57;
  public static final int LP = 17;
  public static final int RS = 22;
  public static final int PRINT_NUM = 23;
  public static final int KW_FLOAT2INT = 53;
  public static final int DIV = 16;
  public static final int LL = 24;
  public static final int RP = 18;
  public static final int PLUS = 13;
  public static final int IF = 20;
  public static final int RL = 25;
  public static final int KW_STRING2CHAR = 58;
  public static final int EXP = 35;
  public static final int KW_FLOAT2STRING = 52;
  public static final int LETHAN = 9;
  public static final int ID = 2;
  public static final int KW_CALL = 26;
  public static final int EOF = 0;
  public static final int HEAP = 28;
  public static final int EQUAL = 6;
  public static final int error = 1;
  public static final int KW_CHAR2INT = 54;
  public static final int KW_ARCO = 41;
  public static final int STACK = 29;
  public static final int DEQUAL = 7;
  public static final int MOD = 34;
  public static final int ERROR = 33;
  public static final int KW_OVALO = 43;
  public static final int PCOMA = 4;
  public static final int KW_RECTANGULO = 42;
  public static final int KW_POLIGONO = 44;
  public static final int KW_VOID = 37;
  public static final int GOTO = 19;
  public static final int NEQUAL = 12;
  public static final int FLOAT = 36;
  public static final int KW_BOOLEAN2INT = 61;
  public static final int THEN = 46;
  public static final int DPUNTOS = 5;
  public static final int KW_INT2STRING = 50;
  public static final int PRINT_CHAR = 38;
  public static final int KW_INT2CHAR = 48;
}

