package com.github.gg;

public enum TOperation {

    DEF_CLASS, DEF_METHOD, DEF_LOCALVAR, IMPORT, BREAK, STMT_SWITCH,
    STMT_FOR, STMT_IF, STMT_NEW_OBJECT, SET_VAR, STMT_WHILE, STMT_DOWHILE,
    ERROR_LEXICO, ERROR_SINTACTICO, DEF_FIELD, DEF_CONSTRUCT, DEF_PARAMETER,
    RETURN, CONTINUE, LEAF, EXP, PLUS, MINUS, MULT, DIV, MOD, BTHAN, BETHAN,
    LETHAN, LTHAN, AND, OR, NOT, NEQUAL, DEQUAL, LMINUS, RMINUS, LPLUS, RPLUS,
    RRPLUS, RRMINUS, LLPLUS, LLMINUS, CAST, NEW, METHOD_CALL, TERNARY,
    PRINT,PRINTLN,NM_LINEA,NM_TEXTO,NM_OVALO,NM_POLIGONO,NM_LIENZO,NM_RECTANGULO,
    NM_ARCO,GOTO,COMMENT,LABEL,PRINT_CHAR,PRINT_NUM,PRINT_BOOLEAN
}
