package com.github.gg;

public enum TOperation {

    DEF_CLASS, DEF_METHOD, DEF_LOCALVAR, IMPORT, BREAK, STMT_SWITCH,
    STMT_FOR, STMT_IF, STMT_NEW_OBJECT, SET_VAR, STMT_WHILE, STMT_DO_WHILE,
    ERROR_LEXICO,ERROR_SINTACTICO,DEF_FIELD, DEF_CONSTRUCT, DEF_PARAMETER, RETURN, CONTINUE
}
